// Fallback data to use when the backend is unavailable

export const fallbackNews = [
  {
    id: 1,
    title: "Ekonomide Yeni Gelişmeler: Merkez Bankası Faiz Kararını Açıkladı",
    content:
      "Merkez Bankası bugün gerçekleştirdiği toplantıda faiz oranlarını sabit tutma kararı aldı. Ekonomistler, bu kararın piyasalarda olumlu karşılanacağını öngörüyor.\n\nYapılan açıklamada, enflasyon verilerinin yakından takip edildiği ve gerekli görülmesi halinde ek tedbirlerin alınabileceği belirtildi. Piyasa uzmanları, önümüzdeki aylarda enflasyon verilerine bağlı olarak faiz politikasında değişiklik olabileceğini ifade ediyor.",
    image: "https://www.btsoekonomi.com/upload/merkez-bankasi-yilin-son-faiz-kararini-acikladi-4275.png",
    category: "Ekonomi",
    author: "Ali Yılmaz",
    date: "16 Mayıs 2025",
  },
  {
    id: 2,
    title: "Yeni Eğitim Reformu Meclisten Geçti",
    content:
      "Milli Eğitim Bakanlığı'nın sunduğu reform paketi TBMM'de onaylandı. Reform paketi, eğitim sisteminde köklü değişiklikler içeriyor.\n\nYeni sistemde, öğrencilerin dijital yetkinliklerinin artırılması ve yabancı dil eğitiminin güçlendirilmesi hedefleniyor. Ayrıca, mesleki eğitime daha fazla önem verilecek ve staj imkanları artırılacak. Reform paketinin 2025-2026 eğitim öğretim yılında uygulamaya konulması planlanıyor.",
    image: "https://placehold.co/600x400/png?text=Eğitim+Haberi",
    category: "Eğitim",
    author: "Elif Demir",
    date: "15 Mayıs 2025",
  },
  {
    id: 3,
    title: "Meteor Yağmuru Bu Gece Türkiye'den İzlenebilecek",
    content:
      "Uzmanlar, gece saatlerinde gökyüzünde görsel şölen yaşanacağını söylüyor. Perseid meteor yağmuru, bu gece Türkiye'den çıplak gözle izlenebilecek.",
    image: "https://placehold.co/600x400/png?text=Bilim+Haberi",
    category: "Bilim",
    author: "Burak Yıldız",
    date: "14 Mayıs 2025",
  },
  {
    id: 4,
    title: "Dolar Rekor Seviyeye Ulaştı",
    content:
      "Piyasalarda dalgalanma devam ederken dolar 33 TL'yi gördü. Ekonomistler, küresel ekonomideki belirsizliklerin döviz kurlarını etkilediğini belirtiyor.",
    image: "https://placehold.co/600x400/png?text=Finans+Haberi",
    category: "Ekonomi",
    author: "Mehmet Demir",
    date: "13 Mayıs 2025",
  },
  {
    id: 5,
    title: "Yeni Marvel Filmi Vizyona Girdi",
    content:
      "Hayranların heyecanla beklediği yeni Marvel filmi sinemalarda yerini aldı. Film, ilk gösterim gününde gişe rekoru kırdı.",
    image: "https://placehold.co/600x400/png?text=Kültür+Sanat+Haberi",
    category: "Magazin",
    author: "Zeynep Kaya",
    date: "12 Mayıs 2025",
  },
  {
    id: 6,
    title: "İstanbul'da Deprem Tatbikatı Gerçekleştirildi",
    content:
      "Afet ve Acil Durum Yönetimi Başkanlığı tarafından geniş çaplı bir deprem tatbikatı düzenlendi. Tatbikata binlerce vatandaş ve yüzlerce kurtarma ekibi katıldı.",
    image: "https://placehold.co/600x400/png?text=Gündem+Haberi",
    category: "Dünya",
    author: "Ayşe Yıldız",
    date: "11 Mayıs 2025",
  },
  {
    id: 7,
    title: "Sağlık Bakanlığı Yeni Diyabet İlacını Onayladı",
    content:
      "Yeni ilaç, Tip 2 diyabet hastaları için umut vadeden bir çözüm olabilir. Klinik deneylerde başarılı sonuçlar elde edildi.",
    image: "https://placehold.co/600x400/png?text=Sağlık+Haberi",
    category: "Sağlık",
    author: "Deniz Şahin",
    date: "10 Mayıs 2025",
  },
  {
    id: 8,
    title: "Futbol Ligi'nde Heyecan Devam Ediyor",
    content:
      "Süper Lig'de bu hafta oynanan derbi maç büyük çekişmeye sahne oldu. Karşılaşma 2-2'lik beraberlikle sonuçlandı.",
    image: "https://placehold.co/600x400/png?text=Spor+Haberi",
    category: "Spor",
    author: "Can Özkan",
    date: "9 Mayıs 2025",
  },
  {
    id: 9,
    title: "Yapay Zeka ile Kanser Teşhisinde Yeni Dönem",
    content:
      "Araştırmacılar, yapay zeka destekli tanı sistemlerinin doğruluk oranını artırdığını açıkladı. Sistem, erken teşhis konusunda umut vadediyor.",
    image: "https://placehold.co/600x400/png?text=Bilim+Haberi",
    category: "Bilim",
    author: "Ahmet Kara",
    date: "8 Mayıs 2025",
  },
  {
    id: 10,
    title: "Turizmde Sezon Umut Vadediyor",
    content:
      "Otellerdeki rezervasyonlar geçen yıla göre %40 artış gösterdi. Turizm sektörü temsilcileri, bu yılın rekor bir sezon olacağını öngörüyor.",
    image: "https://placehold.co/600x400/png?text=Turizm+Haberi",
    category: "Ekonomi",
    author: "Selin Yılmaz",
    date: "7 Mayıs 2025",
  },
]

export const fallbackFinance = [
  {
    id: 1,
    name: "DOLAR",
    value: 37.98,
    change: 0.18,
    changePercent: 0.48,
  },
  {
    id: 2,
    name: "EURO",
    value: 41.68,
    change: -0.23,
    changePercent: -0.55,
  },
  {
    id: 3,
    name: "STERLİN",
    value: 49.01,
    change: -1.63,
    changePercent: -3.32,
  },
  {
    id: 4,
    name: "BİTCOİN",
    value: 82671.78,
    change: 1234.56,
    changePercent: 1.51,
  },
  {
    id: 5,
    name: "BİST 100",
    value: 9379.83,
    change: -102.34,
    changePercent: -1.09,
  },
  {
    id: 6,
    name: "ALTIN",
    value: 2710.58,
    change: -62.27,
    changePercent: -2.3,
  },
  {
    id: 7,
    name: "FAİZ",
    value: 56.0,
    change: 0.23,
    changePercent: 0.5,
  },
]

export const fallbackWeather = {
  istanbul: [
    {
      id: 1,
      date: "16 Mayıs",
      temperature: 24.0,
      condition: "Sunny",
      icon: "sun",
      city: "Istanbul",
    },
    {
      id: 2,
      date: "17 Mayıs",
      temperature: 22.0,
      condition: "Partly Cloudy",
      icon: "cloud-sun",
      city: "Istanbul",
    },
    {
      id: 3,
      date: "18 Mayıs",
      temperature: 19.0,
      condition: "Rainy",
      icon: "cloud-rain",
      city: "Istanbul",
    },
    {
      id: 4,
      date: "19 Mayıs",
      temperature: 21.0,
      condition: "Cloudy",
      icon: "cloud",
      city: "Istanbul",
    },
    {
      id: 5,
      date: "20 Mayıs",
      temperature: 23.0,
      condition: "Sunny",
      icon: "sun",
      city: "Istanbul",
    },
  ],
  ankara: [
    {
      id: 6,
      date: "16 Mayıs",
      temperature: 22.0,
      condition: "Sunny",
      icon: "sun",
      city: "Ankara",
    },
    {
      id: 7,
      date: "17 Mayıs",
      temperature: 20.0,
      condition: "Partly Cloudy",
      icon: "cloud-sun",
      city: "Ankara",
    },
    {
      id: 8,
      date: "18 Mayıs",
      temperature: 17.0,
      condition: "Rainy",
      icon: "cloud-rain",
      city: "Ankara",
    },
    {
      id: 9,
      date: "19 Mayıs",
      temperature: 19.0,
      condition: "Cloudy",
      icon: "cloud",
      city: "Ankara",
    },
    {
      id: 10,
      date: "20 Mayıs",
      temperature: 21.0,
      condition: "Sunny",
      icon: "sun",
      city: "Ankara",
    },
  ],
  izmir: [
    {
      id: 11,
      date: "16 Mayıs",
      temperature: 26.0,
      condition: "Sunny",
      icon: "sun",
      city: "Izmir",
    },
    {
      id: 12,
      date: "17 Mayıs",
      temperature: 24.0,
      condition: "Partly Cloudy",
      icon: "cloud-sun",
      city: "Izmir",
    },
    {
      id: 13,
      date: "18 Mayıs",
      temperature: 21.0,
      condition: "Rainy",
      icon: "cloud-rain",
      city: "Izmir",
    },
    {
      id: 14,
      date: "19 Mayıs",
      temperature: 23.0,
      condition: "Cloudy",
      icon: "cloud",
      city: "Izmir",
    },
    {
      id: 15,
      date: "20 Mayıs",
      temperature: 25.0,
      condition: "Sunny",
      icon: "sun",
      city: "Izmir",
    },
  ],
  antalya: [
    {
      id: 16,
      date: "16 Mayıs",
      temperature: 28.0,
      condition: "Sunny",
      icon: "sun",
      city: "Antalya",
    },
    {
      id: 17,
      date: "17 Mayıs",
      temperature: 26.0,
      condition: "Partly Cloudy",
      icon: "cloud-sun",
      city: "Antalya",
    },
    {
      id: 18,
      date: "18 Mayıs",
      temperature: 23.0,
      condition: "Rainy",
      icon: "cloud-rain",
      city: "Antalya",
    },
    {
      id: 19,
      date: "19 Mayıs",
      temperature: 25.0,
      condition: "Cloudy",
      icon: "cloud",
      city: "Antalya",
    },
    {
      id: 20,
      date: "20 Mayıs",
      temperature: 27.0,
      condition: "Sunny",
      icon: "sun",
      city: "Antalya",
    },
  ],
  bursa: [
    {
      id: 21,
      date: "16 Mayıs",
      temperature: 23.0,
      condition: "Sunny",
      icon: "sun",
      city: "Bursa",
    },
    {
      id: 22,
      date: "17 Mayıs",
      temperature: 21.0,
      condition: "Partly Cloudy",
      icon: "cloud-sun",
      city: "Bursa",
    },
    {
      id: 23,
      date: "18 Mayıs",
      temperature: 18.0,
      condition: "Rainy",
      icon: "cloud-rain",
      city: "Bursa",
    },
    {
      id: 24,
      date: "19 Mayıs",
      temperature: 20.0,
      condition: "Cloudy",
      icon: "cloud",
      city: "Bursa",
    },
    {
      id: 25,
      date: "20 Mayıs",
      temperature: 22.0,
      condition: "Sunny",
      icon: "sun",
      city: "Bursa",
    },
  ],
}
